// <auto-generated />
namespace Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ProductBillid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductBillid));
        
        string IMigrationMetadata.Id
        {
            get { return "202406052046065_Product+Billid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
